name: ${name}
version: ${version}
main: dev.pcrykh.PcrykhPlugin
api-version: "1.21"
commands:
  pcrykh:
    description: Opens the main menu.
    permission: pcrykh.use
permissions:
  pcrykh.use:
    description: Allows access to the main menu.
    default: true
