name: ${name}
version: ${version}
main: dev.pcrykh.PcrykhPlugin
api-version: '1.21'
commands:
  pcrykh:
    description: Pcrykh status
    permission: pcrykh.use
permissions:
  pcrykh.use:
    description: Allows /pcrykh
    default: true
